# Generated by Django 5.1.7 on 2026-02-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('college', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=10)),
                ('employed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
            ],
        ),
    ]
